### ISSUE TITLE
LumenReflections.h(54): fatal error C1001: Internal compiler error.

### ISSUE THREAD

**Issue by gvindiol** [microsoft/WorldLockingTools-Unreal#2]
I'm currently unable to build WLT_Project for the Hololens to test QR Space Pins. 

Unreal Engine - Version 5.0.3
Binary Configuration - Development, Release
Microsoft Visual Studio Community 2022 (64-bit) - Version 17.3.5
Windows 10 SDK - Version 10.0.22000.0

> UATHelper: Packaging (HoloLens): [3/11] Compile Module.Renderer.9_of_22.cpp
> UATHelper: Packaging (HoloLens): N:\UnrealEngine-5.0.3-release\Engine\Source\Runtime\Renderer\Private\Lumen\LumenReflections.h(54): fatal error C1001: Internal compiler error.
> UATHelper: Packaging (HoloLens): (compiler file 'D:\a\_work\1\s\src\vctools\Compiler\CxxFE\sl\p1\c\trees.c', line 11371)
> UATHelper: Packaging (HoloLens):  To work around this problem, try simplifying or changing the program near the locations listed above.
> UATHelper: Packaging (HoloLens): If possible please provide a repro here: https://developercommunity.visualstudio.com
> UATHelper: Packaging (HoloLens): Please choose the Technical Support command on the Visual C++
> UATHelper: Packaging (HoloLens):  Help menu, or open the Technical Support help file for more information
> UATHelper: Packaging (HoloLens): [4/11] Compile Module.Renderer.7_of_22.cpp
> UATHelper: Packaging (HoloLens): N:\UnrealEngine-5.0.3-release\Engine\Source\Runtime\Renderer\Private\Lumen\LumenReflections.h(54): fatal error C1001: Internal compiler error.
> UATHelper: Packaging (HoloLens): (compiler file 'D:\a\_work\1\s\src\vctools\Compiler\CxxFE\sl\p1\c\trees.c', line 11371)
> UATHelper: Packaging (HoloLens):  To work around this problem, try simplifying or changing the program near the locations listed above.
> UATHelper: Packaging (HoloLens): If possible please provide a repro here: https://developercommunity.visualstudio.com
> UATHelper: Packaging (HoloLens): Please choose the Technical Support command on the Visual C++
> UATHelper: Packaging (HoloLens):  Help menu, or open the Technical Support help file for more information
> UATHelper: Packaging (HoloLens): BUILD FAILED
> PackagingResults: Error: Unknown Error

**Comment by fieldsJacksonG** [comment]
We have seen this with an older MSVC ARM toolchain.
You should be able to resolve this by updating to the latest toolchain in the Visual Studio Installer

**Comment by gvindiol** [comment]
Thanks, i was able to compile for Hololens after updating visual studio and grabbing latest MSVC toolchains.
![image](https://user-images.githubusercontent.com/44582391/201759958-c042170f-64af-4826-9a79-cb1952b5a1ef.png)

**Comment by Kean4711DUB** [comment]
Thank you!! you are a life saver. Have been dealing with one issue after another for almost a week, and I keep getting further but there's always something new stopping me from creating these hololens apps. So again thank you. 
Edit: I spoke too soon, issue still exists.
Edit 2: I found the issue, unreal will default to old build tools if they are present and visual studio will tell you to redownload the old ones because they're missing which is not true. so this in fact works
